# Generated by Django 5.0.4 on 2024-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_img',
            field=models.ImageField(default='profile/avatar.png', upload_to='profile_pics/'),
        ),
    ]
