# Generated by Django 5.0.4 on 2024-05-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_img',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='profile/avatar.png', upload_to='profile_pics/'),
        ),
    ]
