# Generated by Django 5.0.4 on 2024-07-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_date_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_shipped',
        ),
    ]
